[WIP] Only upload Prod containers when Version is updated
cds-snc/covid-alert-portal pull request #236
Opened 2020-09-23 17:31 UTC by pcraig3

⚠️ don't merge pls, just testing right now ⚠️

2020-09-23 18:59 UTC, pcraig3 commented on .github/workflows/staging-deploy.yml
> -    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
Pretty sure this is just duplicating the conditional at the top of the file:

```
on:
  push:
    branches: [main]
```

2020-09-23 20:23 UTC, bryan-robitaille requested changes
I think we can tweak these a little more.  Let's chat tomorrow during our Dev stand up to quickly go over some possible changes.

2020-09-23 20:23 UTC, bryan-robitaille commented on .github/workflows/build-container.yml
> +  terraform-security-scan:
Thinking we can drop this `terraforom-security-scan` as it's already running in the Terraform.yml flow on any PR's that touch the `config/terraform/aws` path as well as any pushes to `main`

2020-09-23 20:23 UTC, bryan-robitaille commented on .github/workflows/build-container.yml
> +      - name: Checkout
Not sure if the remaining actions `Checkout, Read VERSION file, Build COVID Portal` are still required in this file.
The `Build COVID Portal` action is duplicated in both the prod-push-container and staging-build-push-container

2020-09-23 20:23 UTC, bryan-robitaille commented on .github/workflows/build-container.yml
> +    steps:
These 3 wait actions should be moved to `prod-push` and `staging-build-push` and this file can be deleted.  The two build and push actions are currently not waiting for the Python checks to pass.

2020-09-23 20:23 UTC, bryan-robitaille commented on .github/workflows/prod-push-container.yml
> +          docker tag base $PROD_ECR_REGISTRY:$VERSION
Nice!  I didn't think of loading the version file to tag the image.

2020-09-23 21:14 UTC, pcraig3 commented on .github/workflows/build-container.yml
> +  terraform-security-scan:
Okay, removed.

2020-09-23 21:15 UTC, pcraig3 commented on .github/workflows/build-container.yml
> +      - name: Checkout
You're right. I was thinking that we could save time by building it once. I think (🤔 ) that the container is built in the same place, so building it twice in the staging + prod actions is wasted effort.

2020-09-23 21:16 UTC, pcraig3 commented on .github/workflows/build-container.yml
> +    steps:
Pushed an update to test if waiting starts working.

2020-09-23 21:16 UTC, pcraig3 commented on .github/workflows/prod-push-container.yml
> +          docker tag base $PROD_ECR_REGISTRY:$VERSION
👍  it's great! been working so far.

2020-09-23 21:37 UTC, pcraig3 commented on .github/workflows/build-container.yml
> +    steps:
You were right all along. New update does what you suggested.

2020-09-23 21:38 UTC, pcraig3 commented on .github/workflows/build-container.yml
> +      - name: Checkout
Nope, you were right. Removed this file.

2020-09-23 21:39 UTC, pcraig3 commented on .github/workflows/prod-build-push-container.yml
> +  PROD_ECR_REGISTRY: ${{ secrets.PROD_ECR_REGISTRY }}
@bryan-robitaille, I was wondering why this one is different than the staging one though. Ie, here the value is a secret vs in staging we wait for the output of a previous step. Shouldn't we do it the same way in both files?

2020-09-24 14:55 UTC, bryan-robitaille commented on .github/workflows/prod-build-push-container.yml
> +  PROD_ECR_REGISTRY: ${{ secrets.PROD_ECR_REGISTRY }}
Was just following the Server teams precedent in which everything regarding Prod seems to be secret.

2020-09-25 16:30 UTC, pcraig3 commented on .github/workflows/prod-build-push-container.yml
> +  PROD_ECR_REGISTRY: ${{ secrets.PROD_ECR_REGISTRY }}
Yup, all good. If we get the variable from the past command, we can remove the secret in this repo.

2020-09-25 17:03 UTC, pcraig3 commented
Okay, all good. Tested this merging onto another branch and both jobs ran. Should be good to merge.

2020-09-25 18:32 UTC, bryan-robitaille approved these changes
Awesome!  Let's get this merged 🎉

2020-09-25 18:43 UTC, merged