Separate the sign up process into 2 steps
cds-snc/covid-alert-portal pull request #299
Opened 2020-10-28 20:00 UTC by bryan-robitaille

This PR removes the mobile number from the original registration step and creates and additional page for the mobile number entry.  This is in preparation for the potential of using Static Security Codes.

🎥  🎉  ...............................Get your popcorn ready! .......................................🎉  🎥 
![Portal_signup](https://user-images.githubusercontent.com/25329319/97489860-7c57f680-1936-11eb-9184-4f8c04b02869.gif)

2020-10-28 20:09 UTC, bryan-robitaille commented
Okay, going to update the tests tomorrow to change the assertion now that the flow of the sign up has changed

2020-10-29 14:36 UTC, pcraig3 requested changes
Hello!

Looks good for the most part. I did manage to break the app by trying to visit another URL while still halfway through the signup process (pic below). 

The reason for this is that trying to see the "/start" page, for example, redirects to the 2fa page, and then it looks for the sms token (whoops, no phone == exception!!).

To me it looks like a new `if` check somewhere in the `login-2fa` route, but maybe there's a cleverer way.

Since it was a bug, we should probably also do a test for this.

## error message
<img width="924" alt="Screen Shot 2020-10-29 at 10 13 19 AM" src="https://user-images.githubusercontent.com/2454380/97588063-7dd6fc80-19d2-11eb-9ecd-85fa8e8eddb9.png">

## here's the stack trace
<img width="630" alt="Screen Shot 2020-10-29 at 10 13 31 AM" src="https://user-images.githubusercontent.com/2454380/97588036-744d9480-19d2-11eb-931a-d3ccd828fa16.png">

2020-10-29 14:36 UTC, pcraig3 commented on profiles/forms.py
>      password1.error_messages["required"] = validation_messages["password"]["required"]
I know it's not part of your PR, but this is something I did by accident in a past PR. If you name these both `password`, instead of `password1`, then it should render as expected.

2020-10-29 14:36 UTC, pcraig3 commented on profiles/signals.py
> +    if not created and instance._pre_save_instance.phone_number:
What is this new condition?

2020-10-29 14:36 UTC, pcraig3 commented on profiles/views.py
> +        return super().get(request, *args, **kwargs)
The signup form prevents you from seeing it once your token is gone. (eg, once your account is created, you can't revisit the signup URL). I was thinking we could do the same here, but I don't know if it actually makes a difference. This page is equivalent of the /edit/phone-number page basically. 🤷 

What do you think?

2020-10-29 14:58 UTC, bryan-robitaille commented on profiles/forms.py
>      password1.error_messages["required"] = validation_messages["password"]["required"]
Will create a new PR for this as it's needed more ugently then this feature

2020-10-29 15:19 UTC, bryan-robitaille commented on profiles/signals.py
> +    if not created and instance._pre_save_instance.phone_number:
This new condition is needed because the HealthcareUser object is created in the DB on the first signup step with `' '` as the phone number.  With the previous logic when the phone number was entered on the 2nd signup step the function would throw an error because the `old_number` was not a string and tried to perform an `.as_e164` conversion.  It would also fail because the query to find the sms_device would return `None` for the `old_number`.  I played around with various logic combinations and finally landed on this one as the easiest to read.  So new logic is basically:
Is the record already existing and does not have a previous value of `' '` ?  Then find the existing old number in the sms_devices and replace it.  Else just create the new sms_device.

2020-10-29 15:38 UTC, bryan-robitaille commented on profiles/views.py
> +        return super().get(request, *args, **kwargs)
Just added a new rule that will bring a user back to the signup-2fa page if they manage to navigate away from the page before inputting a mobile number.  It's essentially an edit/phone-number page but at least it keeps you locked at that page and requires input before you can access the rest of the portal.

2020-10-29 16:30 UTC, pcraig3 approved these changes
Looks good!

2020-10-29 16:40 UTC, merged