View backup codes from account page 👀
cds-snc/covid-alert-portal pull request #311
Opened 2020-11-09 15:20 UTC by pcraig3

This PR changes things up so that we are able to view our backup codes from account page, and then generate new codes on the `/backup-codes` page.

Only when we have no backup codes do we offer to generate them from the account page.

## Screenshots

### account page

| before | after |
|--------|-------|
|   "Get Security Codes" will generate 5 new codes     |  "View security codes" will show you your existing codes.     |
|   <img width="1481" alt="Screen Shot 2020-11-09 at 10 16 55 AM" src="https://user-images.githubusercontent.com/2454380/98559778-09734780-2275-11eb-9178-ffd46ab8d59d.png">  | <img width="1481" alt="Screen Shot 2020-11-09 at 10 15 43 AM" src="https://user-images.githubusercontent.com/2454380/98559781-09734780-2275-11eb-8c34-4439925b4b3f.png">   |

### backup code page

| before | after |
|--------|-------|
|  "view portal" button at the bottom      |  "generate new codes" button at the bottom     |
|  <img width="1481" alt="Screen Shot 2020-11-09 at 10 18 01 AM" src="https://user-images.githubusercontent.com/2454380/98559763-05472a00-2275-11eb-82d4-543f9972901d.png">   | <img width="1481" alt="Screen Shot 2020-11-09 at 10 17 59 AM" src="https://user-images.githubusercontent.com/2454380/98559774-08421a80-2275-11eb-8715-7a71d449d000.png">    |

2020-11-09 20:27 UTC, bryan-robitaille requested changes
Just a quick `makemessages -l fr` and `compilemessages` should do the trick to fix the internationalization issues.

2020-11-09 20:27 UTC, bryan-robitaille commented on backup_codes/templates/backup_codes/backup_codes_list.html
> +  <h1>{% trans "Security codes" %}</h1>
Need to add translation

2020-11-09 20:27 UTC, bryan-robitaille commented on backup_codes/templates/backup_codes/backup_codes_list.html
> +      <button type="submit">{% trans "Get new security codes" %}</button>
Needs translation entry

2020-11-09 20:27 UTC, bryan-robitaille commented on backup_codes/templates/backup_codes/backup_codes_list.html
> +    <a href="{% url 'user_profile' pk=user.id %}" class="secondary" role='button' draggable='false'>{% trans "Back to your account" %}</a>
Needs translation entry

2020-11-09 20:27 UTC, bryan-robitaille commented on profiles/templates/profiles/healthcareuser_detail.html
> +                {% if security_code_count == 1 %}{% trans "code" %}{% else %}{% trans "codes" %}{% endif %}
Needs translation entry

2020-11-09 20:27 UTC, bryan-robitaille commented on profiles/templates/profiles/healthcareuser_detail.html
> +                    <button type="submit" class="link">{% trans "Get security codes" %}</button>
Needs translation entry

2020-11-09 20:27 UTC, bryan-robitaille commented on profiles/templates/profiles/healthcareuser_detail.html
> +                  <a href="{% url 'backup_codes' %}">{% trans "View security codes" %}</a>
Needs translation entry

2020-11-10 13:18 UTC, bryan-robitaille approved these changes

2020-11-10 13:19 UTC, bryan-robitaille commented
I went ahead and fixed two entries that weren't translating on the backup_list view.  The two buttons on the page still had `fuzzy` entries.

2020-11-10 15:19 UTC, pcraig3 commented
Thanks!

2020-11-10 15:19 UTC, merged