[WIP] Backup Codes login flow functionality
cds-snc/covid-alert-portal pull request #313
Opened 2020-11-09 19:38 UTC by bryan-robitaille

Super long PR message to come

2020-11-12 19:55 UTC, bryan-robitaille commented
Just need to finish content now

2020-11-13 20:00 UTC, pcraig3 requested changes
Hooray! This is nearly there I feel like. (most of my comments are musings) 

2 things I noticed though:

1. We should lowercase and remove spaces from the codes when they are submitted. Right now, putting in uppercase characters or a space in the middle causes it to fail.
2. If you don't have any codes left on the login screen, the app breaks (might just be because it's in DEBUG mode and it looks for a code to put in the input field). Seems very fixable.

<img width="859" alt="Screen Shot 2020-11-13 at 2 58 01 PM" src="https://user-images.githubusercontent.com/2454380/99115774-f20fc380-25c0-11eb-8ea1-ec878e9a496f.png">

2020-11-13 20:17 UTC, bryan-robitaille commented on backup_codes/forms.py
> +            self.fields[field].widget.attrs.update({"autocomplete": "off"})
I did originally but then decided against it because we're basically creating a separate 'backup_codes' app.  I was thinking of keeping it along the lines as being standalone as much as possible.
It's an easy fix if you want to go that route of minimal duplication.

2020-11-13 20:18 UTC, bryan-robitaille commented on backup_codes/tests.py
> +        self.assertTrue(response.context["user"].is_verified)
It could end up at the 'welcome' or the 'start' page which is why this test only checks to make sure that the 2fa succeeded and you're completely logged in.

2020-11-13 20:19 UTC, bryan-robitaille commented on backup_codes/tests.py
> +            "province": HealthcareProvince.objects.get(abbr="ON"),
I just needed a dummy user to pass to the Invitation.create() function.  I can set it to 'MB' to align with the invitee.

2020-11-13 20:22 UTC, bryan-robitaille commented on backup_codes/tests.py
> +    def test_users_admin_displayed_on_backup_code_help_page(self):
Good idea

2020-11-13 20:25 UTC, bryan-robitaille commented on profiles/templates/profiles/2fa.html
> +    {% endif %}
They still can.  From the Resend SMS code page there is a link to ask an admin from codes if you can't receive SMS.

2020-11-13 20:27 UTC, bryan-robitaille commented on profiles/views.py
> +            and self.request.user.staticdevice_set.exists()
This checks to see if there is a Static Device.  A Static Device can have zero tokens.  This just ensures the logic below doesn't fail when it checks the token_set.

2020-11-13 20:27 UTC, bryan-robitaille commented on profiles/views.py
Ok

2020-11-13 20:28 UTC, bryan-robitaille commented on profiles/views.py
> +        backup_being_throttled = False
It was simpler but I refactored it to ensure that it could handle all edge cases.  I'll see if I can massage it more.

2020-11-13 20:29 UTC, bryan-robitaille commented on profiles/views.py
> +                code_verfied, sms_being_throttled = verify_user_code(
Good catch, copy and paste error

2020-11-13 20:35 UTC, bryan-robitaille commented on backup_codes/tests.py
> +            HTTP_USER_AGENT="test-browser",
Apparently not.  Removed.

2020-11-13 20:39 UTC, bryan-robitaille commented on profiles/templates/profiles/2fa.html
> +    {% endif %}
Done.

2020-11-13 20:42 UTC, bryan-robitaille commented on backup_codes/views.py
> +        )
No wasn't necessary.

2020-11-13 20:43 UTC, bryan-robitaille commented on backup_codes/views.py
> +    return token_count
Used your suggestion to cut down on lines.

2020-11-13 20:48 UTC, bryan-robitaille commented on profiles/views.py
> +            return False
Used your suggestion

2020-11-13 21:17 UTC, bryan-robitaille commented on backup_codes/tests.py
> +            "province": HealthcareProvince.objects.get(abbr="ON"),
Changed to be 'MB' for province

2020-11-13 21:28 UTC, pcraig3 commented on backup_codes/forms.py
> +            self.fields[field].widget.attrs.update({"autocomplete": "off"})
Minimal duplication! Let's import if we need to (the `profiles/views.py` imports some of the backup_code stuff too.

2020-11-13 21:28 UTC, pcraig3 commented on backup_codes/tests.py
> +        self.assertTrue(response.context["user"].is_verified)
hmm, okay fair enough.

2020-11-13 21:30 UTC, pcraig3 commented on profiles/templates/profiles/2fa.html
> +    {% endif %}
Ah, gotcha. Good to know!

2020-11-16 14:17 UTC, bryan-robitaille commented on backup_codes/forms.py
> +            self.fields[field].widget.attrs.update({"autocomplete": "off"})
Done.

2020-11-16 14:29 UTC, bryan-robitaille commented on profiles/views.py
> +        if self.has_mobile:
Took a second look approach and cleaned up the logic. Much cleaner now.
A child function was already handling the one or many which allowed me to remove the logic from this function.

2020-11-16 14:35 UTC, bryan-robitaille commented
Ready for another review
👀

2020-11-16 15:49 UTC, pcraig3 approved these changes
This looks great! Let's get it merged.

2020-11-16 16:07 UTC, merged