Add a "backup codes" page to the signup
cds-snc/covid-alert-portal pull request #315
Opened 2020-11-12 20:07 UTC by pcraig3

This PR
- adds a "No mobile phone?" button on the signup screen (behind a flag)
- adds a new "Backup codes" page you can visit if you click the link 
- changes some of the internal url names so that they're always underscores (whereas the url paths users see are always hyphens)
- refactors some CSS in anticipation of the backup codes reusing some of the same CSS we use elsewhere
- adds tests

The most interesting part of this PR is the extra button in the form problem.

<details>
<summary>Read more about the "extra button in the form" problem</summary>
<div>
<br />
Added a "No mobile phone button" and a new screen that generates codes.

Technically this should be a POST request because "GET"ting more codes destroys the previous codes, so it's not just a read. However, it was a bit of a conundrum because the other button was already in a form.

In order to keep the buttons beside each other without resorting to some weird positioning, I just created the second button as link.

Nested forms are bad HTML:

```
<form action="/url1">
<button type="submit">Submit</button>
<form action="/url2"><button type="submit>No? Do this other thing</button></form>
</form>
```

There's apparently a form attribute that you can set on input elements, specifiying the form to activate:
- https://www.sitepoint.com/the-html5-form-attribute/

However, it's not supported in IE11 or lower, and we can't realistically drop support for IE11.

So yeah, made it a GET request -- seemed like the best of bad options.
</div>
</details> 

## Fun gif!

![signup](https://user-images.githubusercontent.com/2454380/98990289-41d68800-24f8-11eb-9402-4bea0250cf34.gif)

2020-11-13 14:31 UTC, bryan-robitaille requested changes
I noticed 2 things..
The first is the `Next` button on the `signup_backup_codes_list`.  It doesn't seem to perform any action.
The second is that although the user is created without a phone number associated to them (phone_number is not required on the model) the super admin view doesn't allow the HealthcareUser to be saved without one.  If we're making the phone_number non-required now we should probably ensure both admins and super admins can modify/save a users profile without the `phone_number` filed being required

2020-11-13 14:31 UTC, bryan-robitaille commented on backup_codes/templates/backup_codes/signup_backup_codes_list.html
> +    <a href="#" role='button' draggable='false'>{% trans "Next" %}</a>
This button doesn't seem to perform any action.  After clicking on the button it remains on the same page.

![Signup_2fa](https://user-images.githubusercontent.com/25329319/99082705-7d259500-2592-11eb-8152-cc2ed2cef06d.gif)

2020-11-13 15:28 UTC, pcraig3 commented on backup_codes/templates/backup_codes/signup_backup_codes_list.html
> +    <a href="#" role='button' draggable='false'>{% trans "Next" %}</a>
Yeah, this is on purpose — I'm waiting for the login story to be completed first (ie, the next screen would be "use a 2fa code to log in").

2020-11-13 18:08 UTC, bryan-robitaille commented on backup_codes/templates/backup_codes/signup_backup_codes_list.html
> +    <a href="#" role='button' draggable='false'>{% trans "Next" %}</a>
The 2fa view is the same are the current one.  The existing view accepts both SMS and Backup Codes.  `<a href="{% url 'login_2fa'}" role='button' draggable='false'>{% trans "Next" %}</a>` should do the trick.

2020-11-13 23:03 UTC, pcraig3 commented on backup_codes/templates/backup_codes/signup_backup_codes_list.html
> +    <a href="#" role='button' draggable='false'>{% trans "Next" %}</a>
Updated!

2020-11-13 23:06 UTC, pcraig3 commented
I think the phone number problem is mitigated by the new migration. 

> Users and admins will not be able to remove phone numbers once set, but are able to create accounts without initially setting a phone number.

> However, superadmins are able to remove phone numbers using the Django admin backend.

There's a weird account page now for phone numbers if they're empty (it just says "change" — should probably say "add a phone number" or something, but it's still all behind a feature flag so we can fix that later I think.)

2020-11-13 23:08 UTC, pcraig3 commented
Shoot, I just noticed a problem. You can't get to the 2FA screen without the logic you're adding in your PR.

2020-11-16 14:44 UTC, bryan-robitaille approved these changes

2020-11-16 17:55 UTC, pcraig3 commented
okay, finally merging

2020-11-16 17:55 UTC, merged