[WIP] Announcement Engine
cds-snc/covid-alert-portal pull request #323
Opened 2020-11-24 21:01 UTC by bryan-robitaille

This PR creates an announcement engine that allows for the creation of site wide as well as user specific announcements.

Creating announcements through the admin panel allows to set both FR and EN titles and content as well as publishing widow, specific user or site wide, is dismissible, and whether the announcement is set to active.
![announcements_admin](https://user-images.githubusercontent.com/25329319/100149913-d6cc7000-2e6c-11eb-9d03-b4a123e46a6d.gif)

The users have the ability to dismiss an announcement if set as such for the specific announcement.
![announcement_user](https://user-images.githubusercontent.com/25329319/100150717-0f207e00-2e6e-11eb-8af8-f5c423ad271b.gif)

2020-11-25 22:04 UTC, pcraig3 requested changes
Wow, Django modules are super cool.

This is really good work. 👍 👍 👍 

I found a few little issues but easily remedied (mostly listed in the comments), but one described here.

Normally, you're not logged in on the login page, but if you are, you get a full-bleed message. Also, even when you're not, the messages container has a 20px bottom margin so it pushes down the blue panel.

| before | after |
|--------|-------|
|  full width message when you're logged in on the login page.      |  20px gap between the blue panel and the blue bar at the top     |
|   <img width="1422" alt="Screen Shot 2020-11-25 at 4 33 41 PM" src="https://user-images.githubusercontent.com/2454380/100284603-68a3ae00-2f3d-11eb-8ee0-221a456b673c.png">  |  <img width="1422" alt="Screen Shot 2020-11-25 at 4 33 50 PM" src="https://user-images.githubusercontent.com/2454380/100285153-62620180-2f3e-11eb-9404-14f64ddcd616.png"> |

2020-11-25 22:04 UTC, pcraig3 commented on announcements/static/scss/components/_announcements.scss
> +        position: relative;
When there are several announcements, there's no space between them.

<img width="1422" alt="Screen Shot 2020-11-25 at 4 38 59 PM" src="https://user-images.githubusercontent.com/2454380/100285901-b4efed80-2f3f-11eb-9035-bb82ceefd844.png">

I think you should apply a bottom margin of ~10px using the [`sibling selector`](https://developer.mozilla.org/en-US/docs/Web/CSS/General_sibling_combinator) so that it only applies to `li`s that come after another `li`.

```css
main .announcements ul li ~ li {
margin-bottom: 10px; /*doesn't apply to the first one */
}
```

2020-11-26 16:24 UTC, bryan-robitaille commented on announcements/context_processors.py
> +                if request.LANGUAGE_CODE == "en":
Done.

2020-11-26 16:24 UTC, bryan-robitaille commented on announcements/context_processors.py
> +    """
🎉

2020-11-26 16:28 UTC, bryan-robitaille commented on announcements/models.py
> +    site_wide = models.BooleanField(_("Site Wide"), default=False)
Removing and instead using logic that is no user is set to an announcement then show to everyone.

2020-11-26 16:39 UTC, bryan-robitaille commented on announcements/models.py
> +    display = models.BooleanField(_("Show to users"), default=False)
renamed to is_active

2020-11-26 16:42 UTC, bryan-robitaille commented on announcements/static/css/announcements.css
> +
You actually need it because the current python and docker workflow does not pick this file up and build it.

2020-11-26 16:42 UTC, bryan-robitaille commented on announcements/static/scss/components/_announcements.scss
> +      padding-left: 0px;
Done

2020-11-26 16:44 UTC, bryan-robitaille commented on announcements/templates/announcements/announcements.html
> +            <div class="announcement-content-container" style="width: 90%;">
Good catch, was left over from when I was live styling... (Django doesn't rebuild the CSS on the fly for this module.

2020-11-26 16:45 UTC, bryan-robitaille commented on announcements/templates/announcements/announcements.html
> +                    {{announcement.content|safe}}
User input from the admin panel.... hopefully d'em folks know what they're doing.

2020-11-26 16:51 UTC, bryan-robitaille commented on announcements/views.py
> +        from_url = request.META["HTTP_REFERER"]
Good idea.  Added default back to /start

2020-11-26 16:59 UTC, bryan-robitaille commented on portal/settings.py
> +                "announcements.context_processors.announcement",
Actually neither.  Django allows you to add context_processors that get run on each render.  So we ensure Django uses our context_processor to check for announcements on each page.

2020-11-26 17:09 UTC, bryan-robitaille commented on announcements/static/scss/components/_announcements.scss
> +        position: relative;
Added padding

2020-11-26 19:02 UTC, pcraig3 commented on announcements/static/css/announcements.css
> +
Shoot, okay let's keep it then.

2020-11-26 19:06 UTC, pcraig3 requested changes
Okay! Almost there.

2 small things.

1. There is still a not-run migration here.
2. Version bump. The number depends whether we want to merge the SMTP PR first or this first.

2020-11-26 20:38 UTC, pcraig3 approved these changes
🚀

2020-11-26 20:39 UTC, pcraig3 approved these changes
Awesome work Bryan! 🎉

2020-11-26 20:48 UTC, merged