OTK SMS spike working
cds-snc/covid-alert-portal pull request #357
Opened 2021-01-13 19:15 UTC by andrej-vasilj

# Summary | Résumé

This work is related to sending the one-time-key (OTK) to patients via SMS. When a new key has been generated, portal users will have the option to navigate to a new form that allows them to enter a patient's mobile phone number and send them the generated key via SMS.

To enable this feature, it was necessary to cache the generated key within the server-side session. Currently, when the user navigates back to the start page, the cache is deleted.

# Test instructions | Instructions pour tester la modification

1. Login
2. Generate a key and note the new button "Text key to patient"
3. Fill out your mobile phone number and send the text
4. Ensure that you receive a text message
5. You should be taken to a success page with options to navigate to other pages, ensure that the navigation works

2021-01-15 14:47 UTC, pcraig3 requested changes
Hello! Looks really good overall! 

I've left a bunch of comments here and there: just things that we will want when we eventually merge this into the main branch. 

Let me know if there's anything you want to discuss in particular. At CDS we've been pretty bad at formalizing conventions (eg, form handling, input elements) in a way that's clearly written down, so apologies for the "we tend to do it this way" kinds of comments.

2021-01-15 14:47 UTC, pcraig3 commented on covid_key/templates/covid_key/otk_sms_sent.html
> +  </div>
Can we make this a real form? We can submit it as a POST request to the same URL and then redirect to whatever the submitted `value` is. We try to avoid JS where possible.

You don't have to use `cds_form` if it's too much work. We can just use `<form><fieldset><radios ...><button></form>` since it's the only place we have radios.

2021-01-15 14:47 UTC, pcraig3 commented on covid_key/templates/covid_key/otk_sms_sent.html
> +  </div>
Also we would want to translate the text as well at some point. :)

2021-01-15 14:47 UTC, pcraig3 commented on profiles/static/js/script.js
> +});
This is pretty clever actually, but (mentioned above), we try to use default form interactions instead of JS where possible. We can just rely on the POST request and remove this.

2021-01-15 15:24 UTC, andrej-vasilj commented on covid_key/forms.py
> +class OtkSmsForm(forms.Form):
Great tip!

2021-01-15 15:27 UTC, andrej-vasilj commented on covid_key/forms.py
> +    )
Not sure I understand...you mean in stead of "patient's" it should be "patient`s"? Is there a rationale for that?

2021-01-15 15:27 UTC, andrej-vasilj commented on covid_key/forms.py
> +                    "%b %d %Y %H:%M:%S"
Do you think we could just standardize this? Maybe we have the string formatting string as a setting in the settings file that we can then use everywhere?

2021-01-15 15:29 UTC, andrej-vasilj commented on covid_key/templates/covid_key/otk_sms.html
> +  <h1>{% trans "Text key to patient" %}</h1>
Sure, great tip. I don't think I'll bother trying to abstract that at this point, I'll just paste it in.

2021-01-15 15:30 UTC, pcraig3 commented on covid_key/forms.py
> +    )
Instead of `patient's`, it should say `patient’s`.

2021-01-15 15:31 UTC, andrej-vasilj commented on covid_key/templates/covid_key/otk_sms_sent.html
> +  </div>
Ya I was wondering how you wanted to tackle this. I agree that a form-based solution would make sense.

2021-01-15 15:31 UTC, andrej-vasilj commented on covid_key/urls.py
>          ),
yes you're right, nice catch.

2021-01-15 15:32 UTC, andrej-vasilj commented on covid_key/urls.py
> +        r"otk_sms_sent/(?P<phone_number>[+\d]{0,50})$",
Sure thing.

2021-01-15 15:36 UTC, andrej-vasilj commented on covid_key/views.py
> +class SessionTemplateView(TemplateView):
But that wouldn't describe it's behaviour though. It's a parent view class that checks if we have an otk cached within the session, that's why I called it "SessionTemplateView". I ended up using it in a few places...

2021-01-15 15:37 UTC, andrej-vasilj commented on profiles/static/js/script.js
> +});
Makes sense to me

2021-01-15 15:38 UTC, andrej-vasilj commented on profiles/static/scss/components/_otk.scss
> +    margin: 20px;
I figured things would change there. It was more of a quick approach since it's a spike and since I have no idea how you guys wanted to standardize that

2021-01-15 16:16 UTC, pcraig3 commented on covid_key/forms.py
> +                    "%b %d %Y %H:%M:%S"
I think let's let it live here until we have "final" content. Once we do, it might make sense. For example, we are using a time format on the 'one-time-key' page.

2021-01-15 16:17 UTC, pcraig3 commented on covid_key/views.py
> +class SessionTemplateView(TemplateView):
Okay, fair enough.

2021-01-15 16:21 UTC, pcraig3 commented on profiles/static/scss/components/_otk.scss
> +    margin: 20px;
All good! We pretty much are following this pattern here: https://design-system.service.gov.uk/components/radios/#stacked-radios. 

The links I sent you before are an implementation in JS, but should be fairly portable. But if you wanted the source for the design / the HTML we would use, its the CDS Design System.

2021-01-18 16:09 UTC, pcraig3 commented on covid_key/forms.py
> +    )
It's a typography "good practice" (re: snobby) thing: curly quotes are what you would see in a book or most other professionally printed material. Straight quotes originated in typewriters to save space and are really useful for coding, but they are kind of a stylistic no-no for content.

To take an excerpt from [the Butterick's Typography page](https://typographyforlawyers.com/straight-and-curly-quotes.html):

> Straight quotes are a _typewriter habit_. In traditional printing, all quotation marks were curly. But typewriter character sets were limited by mechanical constraints and physical space. By replacing the curly opening and closing quotes with ambidextrous straight quotes, two slots became available for other characters.

> Word processors are not limited in this way. You can always get curly quotes. Compared to straight quotes, curly quotes are more legible on the page and match the other characters better. Therefore, straight quotes should never, ever appear in your documents.

Basically it comes down to it's the convention we follow.

2021-01-20 18:37 UTC, pcraig3 requested changes
Okay! Looked again. Made a few comments but they shouldn't take long to fix 👍

2021-01-20 18:37 UTC, pcraig3 commented on covid_key/tests.py
> +        self.assertEqual(response.status_code, 302)
We should also do a test with 2 different phone numbers (ie, that it's rejected).

2021-01-20 18:37 UTC, pcraig3 commented on covid_key/urls.py
> +        name="otk_sms_sent",
Is the phone number here used for anything? I am not sure if it is.

2021-01-20 18:37 UTC, pcraig3 commented on portal/templates/includes/radio_select.html
> +        <label {% if option.attrs.id %} for="{{ option.attrs.id }}"{% endif %}>{{ option.label }}</label>
The radios themselves look pretty good, but there's one small usability error: the `for` attribute of `label` has to be the same as the `id` of the `input` for the label to be properly associated with the input. 

So basically add `option.attrs.id` as the `id` of the input.

2021-01-20 18:37 UTC, pcraig3 commented on portal/widgets.py
> +    template_name = "includes/radio_select.html"
This is cool, I haven't seen this done before.

2021-01-20 18:37 UTC, pcraig3 commented on covid_key/forms.py
> +
I should have noticed this, but I didn't.

There isn't currently validation to check that both numbers match each other. I tried entering two badly formatted phone numbers, and I got the error I expected, but if you enter 2 different phone numbers, the form submits correctly and sends a message to the first number entered. 

We should return an error message if the two numbers are different and also write a unit test for this.

2021-01-21 16:38 UTC, andrej-vasilj commented on covid_key/forms.py
> +
Ya for sure, nice catch

2021-01-22 16:26 UTC, andrej-vasilj commented on covid_key/urls.py
> +        name="otk_sms_sent",
I thought I would need it on the final page to say like "this number XXXXXXX was sent a text" but I guess not so I removed it.

2021-01-25 23:20 UTC, pcraig3 reviewed
Just a few small changes to suggest, but it looks good otherwise 👍

2021-01-25 23:20 UTC, pcraig3 commented on covid_key/tests.py
> +        manitoba.save()
can we add a test that going to the `/otk-sms` url for a different province will redirect?

2021-01-25 23:20 UTC, pcraig3 commented on covid_key/forms.py
> +            details={"code": otk["code"]},
Hmm, we should also remove the "FR" template then, since we only have one for this one (and remove "EN" as a suffix"). 🎈 sorry 🍰

2021-01-26 14:41 UTC, andrej-vasilj commented on covid_key/forms.py
> +            details={"code": otk["code"]},
I feel like there still may be some back and forth on that. I would suggest to keep it for now just in case.

2021-01-27 00:21 UTC, andrej-vasilj commented
@pcraig3 I figured out why I need the phone number param in the otk_sms_sent url. It's because on that page we display the text "did {{ phone_number }} receive the text?"

2021-01-28 18:01 UTC, pcraig3 reviewed
Basically, the functionality works just fine, but there content for the [final designs](https://www.figma.com/file/znPqLTQQDcUkaNjdDcShiz/Exposure-Notification---Health-Portal?node-id=6677%3A47081) is quite often different from what's in this PR.

A lot of that predates this PR, for example, many of the changes to the page where the code is displayed initially are new. 

We should definitely update the text within the OTK flow so that it looks like the designs. For the other changes, that could be a separate card or it could be just bundled along here as well.

2021-01-29 18:08 UTC, pcraig3 commented
Okay, slapped a commit on the end updating some of the words (and adding one more check to the form because it would throw an error if there was no value).

I think we could still look at formatting the number so that it looks better (`(416) 667 5327` instead of `+14166675327`), but let's just ship this ⛵

2021-01-29 18:08 UTC, pcraig3 approved these changes

2021-01-29 18:51 UTC, merged