Add registrant email verification
cds-snc/covid-alert-portal pull request #380
Opened 2021-02-15 20:47 UTC by dsamojlenko

# Summary | Résumé

Adds the Registrant email verification step. The flow is as follows:

- User enters email address
- System creates email_confirmation record
- System sends confirmation email
- User clicks link in email
- System ensures confirmation link is valid (expires after 24hrs)
- System creates or gets existing Registrant
- User is redirected to the Name step (pre-populated if registrant already exists)
- System deletes the email_confirmation record
- User continues with Location registration

To test:
- You will need the template_ids for the new Notify Confirmation Email templates (see .env.example, Notify)

2021-02-17 02:04 UTC, andrej-vasilj commented on register/templates/register/error.html
> +  Not Logged in
Not sure if this title property is really relevant for anything, but it should probably have a similar meaning/context as the message...maybe something like "Link expired".

2021-02-17 02:05 UTC, andrej-vasilj commented on register/templates/register/registrant_email_submitted.html
> +  <p>{% trans "If you did not get the email, check your junk or spam folder." %}
Do we have a "send again" functionality planned for this?

2021-02-17 02:09 UTC, andrej-vasilj commented on register/views.py
> +        self.request.session["submitted_email"] = self.submitted_email
I'm wondering if you could just move this line to the function above this. Then you could remove this function all together and use the "success_url" class property instead. It would be a bit more concise. Generally with Django I would only override a class property with its functional form when I need to add extra logic.

2021-02-17 02:15 UTC, andrej-vasilj commented on register/views.py
> +class RegistrantEmailConfirmError(TemplateView):
There's no need for this class. You can just use a template view directly in the url definition.

2021-02-17 02:22 UTC, andrej-vasilj commented on register/views.py
> +        confirm = EmailConfirmation.objects.get(id=pk, created__gt=time_threshold)
While this will definitely work, I think it would be better to get the instance and then explicitly perform the datetime comparison. By using the ORM to perform this comparison we wouldn't know if the exception is due to the date being expired or if for some strange reason the PK was missing from the DB. In this latter case we could still show the user the same error page or maybe even just crash with an error 500. In either case I think it would be nice to be able to log that event if it happened. Like if for example somebody was just trying random PKs as some form of attack? Just thinking out loud here...

2021-02-17 02:27 UTC, andrej-vasilj commented on register/views.py
> +        registrant, created = Registrant.objects.get_or_create(email=confirm.email)
I think we could use the "created" flag here to our advantage and save the registrant's name to the session as well if it already exists. This way we could pre-populate it into the template to save the user a step if they are creating multiple qr codes.

2021-02-17 02:31 UTC, andrej-vasilj commented on portal/.env.example
> +# REGISTER_EMAIL_CONFIRMATION_ID_EN =
Currently if we add a new notify template we have to add it to this env example file and the settings which you have already, and the readme plus like 5 or 6 different infrastructure related files. On top of this we need to remember to add the secret to Github directly (in staging and production) and manually to Heroku. If I remember correctly Paul made a document for this process a few days before you joined. I have no idea where this document is living but maybe Brian would know.

2021-02-17 02:32 UTC, andrej-vasilj requested changes
Nice work overall Dave! I have a few fairly minor comments. Mostly we need to ensure that all of the infrastructure related files are updated to get the new notify template to work.

2021-02-17 15:27 UTC, dsamojlenko commented on register/views.py
> +        confirm = EmailConfirmation.objects.get(id=pk, created__gt=time_threshold)
Refactored a bit to account for logging the different possible errors (expired vs invalid). Still rendering the same error page.

2021-02-17 16:35 UTC, dsamojlenko commented on register/views.py
> +        registrant, created = Registrant.objects.get_or_create(email=confirm.email)
So the Name field already does pre-populate for returning users - not from the session though, from the model- this was leftover from the previous iteration.

2021-02-17 16:53 UTC, dsamojlenko commented on register/views.py
> +class RegistrantEmailConfirmError(TemplateView):
sweet. made the same change to the start page as it was setup the same way.

2021-02-17 19:46 UTC, dsamojlenko commented on register/templates/register/error.html
> +  Not Logged in
We don't have content for this page yet. I've updated it for context to "Invalid or expired link" but that should be replaced by final content later.

2021-02-17 20:04 UTC, dsamojlenko commented on register/templates/register/registrant_email_submitted.html
> +  <p>{% trans "If you did not get the email, check your junk or spam folder." %}
ah yes, missed that button.

2021-02-17 20:05 UTC, dsamojlenko commented on portal/.env.example
> +# REGISTER_EMAIL_CONFIRMATION_ID_EN =
I will hunt that doc down

2021-02-19 13:45 UTC, andrej-vasilj approved these changes
Looks good Dave, thanks for the changes! Are the tests coming afterwards in another PR?

2021-02-19 18:43 UTC, dsamojlenko commented
Merging. Tests will come in another PR.

2021-02-19 18:43 UTC, merged