[WIP] Update registration flow content
cds-snc/covid-alert-portal pull request #382
Opened 2021-02-19 21:50 UTC by dsamojlenko

# Summary | Résumé

> 1-3 sentence description of the changed you're proposing, including a link to a GitHub Issue # or Trello card if applicable.

---

> Description en 1 à 3 phrases de la modification proposée, avec un lien vers le problème (« issue ») GitHub ou la fiche Trello, le cas échéant.

# Test instructions | Instructions pour tester la modification

> Sequential steps (1., 2., 3., ...) that describe how to test this change. This will help a developer test things out without too much detective work. Also, include any environmental setup steps that aren't in the normal README steps and/or any time-based elements that this requires.

---

> Étapes consécutives (1., 2., 3., …) qui décrivent la façon de tester la modification. Elles aideront les développeurs à faire des tests sans avoir à jouer au détective. Veuillez aussi inclure toutes les étapes de configuration de l’environnement qui ne font pas partie des étapes normales dans le fichier README et tout élément temporel requis.

# Help requested | Aide requise

> Things that you (the submitter) want reviewers to pay very close attention to when they review this.

---

> Éléments auxquels vous (le demandeur) souhaitez que les réviseurs prêtent attention lorsqu’ils examineront votre demande.

# Unresolved questions / Out of scope | Questions non résolues ou hors sujet

> Are there any related issues or tangent features you consider out of scope for this issue that could be addressed in the future?

---

> Y a-t-il des questions connexes que vous considérez hors sujet et qui pourraient être abordées plus tard?

# Reviewer checklist | Liste de vérification du réviseur

This is a suggested checklist of questions reviewers might ask during their review | Voici une suggestion de liste de vérification comprenant des questions que les réviseurs pourraient poser pendant leur examen :

- [ ] Does this meet a user need? | Est-ce que ça répond à un besoin utilisateur?
- [ ] Is it accessible? | Est-ce que c’est accessible?
- [ ] Is it translated between both offical languages? | Est-ce dans les deux langues officielles?
- [ ] Is the code maintainable? | Est-ce que le code peut être maintenu?
- [ ] Have you tested it? | L’avez-vous testé?
- [ ] Are there automated tests? | Y a-t-il des tests automatisés?
- [ ] Does this cause automated test coverage to drop? | Est-ce que ça entraîne une baisse de la quantité de code couvert par les tests automatisés?
- [ ] Does this break existing functionality? | Est-ce que ça brise une fonctionnalité existante?
- [ ] Should this be split into smaller PRs to decrease change risk? | Est-ce que ça devrait être divisé en de plus petites demandes de tirage (« pull requests ») afin de réduire le risque lié aux modifications?
- [ ] Does this change the privacy policy? | Est-ce que ça entraîne une modification de la politique de confidentialité?
- [ ] Does this introduce any security concerns? | Est-ce que ça introduit des préoccupations liées à la sécurité?
- [ ] Does this significantly alter performance? | Est-ce que ça modifie de façon importante la performance?
- [ ] What is the risk level of using added dependencies? | Quel est le degré de risque d’utiliser des dépendances ajoutées?
- [ ] Should any documentation be updated as a result of this? (i.e. README setup, etc.) | Faudra-t-il mettre à jour la documentation à la suite de ce changement (fichier README, etc.)?

2021-02-24 15:14 UTC, andrej-vasilj commented on portal/templates/includes/radio_select.html
> +          {% if option.attrs.help_text %}
Great solution! I was thinking along the same lines for this issue

2021-02-24 15:20 UTC, andrej-vasilj commented on register/templates/register/confirmation.html
> +  {% trans "We've got the information for your poster" %}
iirc Paul told me that for whatever reason we should use a diff character for the apostrophes. He recommended ’ instead of '. Not sure if you know anything about that or want to continue that...

2021-02-24 15:21 UTC, andrej-vasilj commented on register/templates/register/confirmation.html
> +    <svg width="104" height="132" viewBox="0 0 104 132" fill="none" xmlns="http://www.w3.org/2000/svg">
Can we maybe serparate out the svg images into their own asset files just for clarity? It's a bit odd to see them directly embedded into the template

2021-02-24 15:24 UTC, andrej-vasilj commented on register/tests.py
>      def test_start_page(self):
You may want to test that the correct template is being rendered for these.

2021-02-24 15:24 UTC, andrej-vasilj commented on register/tests.py
>          r = Registrant.objects.create(email="test@test.com")
I think the negative tests are useful as well. Like what should happen if we don't have the registrant id stored in the session.

2021-02-24 15:36 UTC, andrej-vasilj commented on register/views.py
>          return [TEMPLATES[self.steps.current]]
For this view and beyond we need to have some sort of safeguard that prevents people from accessing these links directly without having confirmed an email. Currently it will just crash with a KeyError when it tries to access the registrant_id from the session which doesn't exist.

2021-02-24 15:38 UTC, andrej-vasilj requested changes
Great PR Dave! Thanks a lot for refactoring the base/footer templates for the register app! I have a few small comments that you can decide whether to do or not and one more crucial one at the end regarding the view access.

2021-02-24 22:24 UTC, dsamojlenko commented on register/templates/register/confirmation.html
> +  {% trans "We've got the information for your poster" %}
might as well, I usually just go with whatever I copy/paste out of designs... maybe I typed this one.

2021-02-24 22:37 UTC, dsamojlenko commented on register/templates/register/confirmation.html
> +    <svg width="104" height="132" viewBox="0 0 104 132" fill="none" xmlns="http://www.w3.org/2000/svg">
... better for caching too. think I put them there for quickness/convenience, but forgot to move them out

2021-02-24 22:41 UTC, dsamojlenko commented on register/tests.py
>      def test_start_page(self):
beauty

2021-02-24 22:42 UTC, dsamojlenko commented on register/views.py
>          return [TEMPLATES[self.steps.current]]
yeah. would a middleware approach be appropriate?

2021-02-25 17:40 UTC, dsamojlenko commented on register/views.py
>          return [TEMPLATES[self.steps.current]]
took a different approach

2021-02-25 21:03 UTC, dsamojlenko commented
Waiting on the Django patch in PR #381 to fix the Snyk error

2021-02-26 01:07 UTC, andrej-vasilj commented on register/tests.py
> +        Switch.objects.create(name="QR_CODES", active=True)
Do we still need this switch for something?

2021-02-26 01:14 UTC, andrej-vasilj commented on register/views.py
> +    def dispatch(self, request, *args, **kwargs):
Great that we have this now! I see that this same function is repeating a few times. It's not a big deal, so feel free to merge as-is, but it would be nice to have that in a single place. Maybe just subclass the TemplateView, add that dispatch method and inherit from it in all of your views?

2021-02-26 01:15 UTC, andrej-vasilj commented on register/tests.py
> +class RegisterEmailConfirmation(TestCase):
That's a lot of new unit tests! Looking good!

2021-02-26 01:15 UTC, andrej-vasilj approved these changes
Looks great Dave, nice PR!. I have a few minor questions/comments, but feel free to merge as-is if you want.

2021-02-26 15:28 UTC, dsamojlenko commented on register/tests.py
> +        Switch.objects.create(name="QR_CODES", active=True)
Good point, no we don't ... removed other references as well

2021-02-26 15:29 UTC, dsamojlenko commented on register/views.py
> +    def dispatch(self, request, *args, **kwargs):
yeah I was trying to figure out the "right way" to re-use, but since it was just a few places figured ok to roll for now, we can refactor later.

2021-02-26 17:04 UTC, merged