Provincial detour page
cds-snc/covid-alert-portal pull request #417
Opened 2021-03-09 16:08 UTC by sakura-sketch

An unavailable detour page for provinces that aren't participated in the QR code registration

2021-03-09 21:12 UTC, dsamojlenko requested changes

2021-03-09 21:12 UTC, dsamojlenko commented on register/views.py
> +    print(included_provinces.__contains__(data.get("province")))
can you remove these print() debugging calls

2021-03-11 16:36 UTC, andrej-vasilj commented on register/forms.py
> +class LocationUnavailableForm(HealthcareBaseForm, forms.Form):
I don't think we need to explicitly declare empty forms here.

2021-03-11 16:37 UTC, andrej-vasilj commented on register/urls.py
> +    ("unavailable", LocationUnavailableForm),
You could probably replace this with ("unavailable", forms.Form) and achieve the same effect...

2021-03-11 16:43 UTC, andrej-vasilj commented on register/views.py
> +    if data.get("province") is not None:
I think it would suffice to use a simple Pythonic construct like:

return data.get('province') not in provinces_list

As a general piece of advice I would suggest to avoid using internal functions like '__contains__' if at all possible. Python doesn't strictly enforce class encapsulation, but the notation of using a single or double underscore indicates the intention to keep something private so it should generally be respected unless there's no other way around.

2021-03-11 16:44 UTC, andrej-vasilj commented on register/views.py
> +        print(self.steps.current)
Probably don't need this print statement anymore?

2021-03-11 16:45 UTC, andrej-vasilj requested changes
Hey, nice work! Looks like it should achieve the desired effect! Just have a few small comments..

2021-03-11 16:49 UTC, sakura-sketch commented on register/views.py
> +    if data.get("province") is not None:
Sure! Thank you so much!

2021-03-11 16:49 UTC, sakura-sketch commented on register/views.py
> +        print(self.steps.current)
Yeah, I missed that one

2021-03-12 14:51 UTC, andrej-vasilj requested changes
Hey Nitya, thanks for the changes. I looked at this PR again and I still have some concerns. I see that your approach will work, but only superficially. I can reach the 'unavailable' page when testing this PR, but I can also just by-pass it by manually entering the next step in the browser url. Like I can just change 'unavailable' for 'category' and there's nothing blocking me from continuing. You'll still have to ensure that the next steps of the process are blocked if the province is not correct. I suggest that you take a look at how I did this for the OTK sms sending and apply the same approach.

2021-03-12 16:18 UTC, andrej-vasilj approved these changes
Sorry I didn't know that the intention was to still allow people to continue with the registration even after seeing the page. It looks like it serves the desired purpose given the new insights!

2021-03-15 14:24 UTC, dsamojlenko approved these changes

2021-03-15 14:28 UTC, merged