Improve interaction design of Date and time selection
cds-snc/covid-alert-portal pull request #486
Opened 2021-04-16 04:49 UTC by dorianjp

Trello:
https://trello.com/c/bNfAPtLt/704-improve-interaction-design-of-date-and-time-selection

Updated form wizard for creating outbreak notifications
* refactored FormView into standard View to simplify complex form logic and context processing
* Enabled multiple submit modes depending on form button submitted
* Enabled time range selection for same-day notification window timeframes
* Save notification data in session with timezone data (force America/Toronto for MVP pilot)
* Validation on form submission to disallow overlapping time ranges in session and in database
* Custom form template page with bespoke logic on errors or warning view for types of ValidationError
* Updated confirm view template to show time ranges

This PR enabled new functionality for time range support whereas previously had whole day based notifications. Other impacts not handled in this PR include:
* no time ranges shown on history view for notifications
* no support for local time zone of user or outbreak location
* no validation of session data / time ranges @ time of database transaction post-> confirmation view

2021-04-16 04:57 UTC, dorianjp commented on outbreaks/forms.py
> +        return tz.localize(datetime(
FYI ran into bugs w datetime().replace(tzinfo):
https://pythonhosted.org/pytz/

tz.localize is more consistent

2021-04-16 04:59 UTC, dorianjp commented on outbreaks/templates/datetime.html
> +    {% if warning_ind %}
Warning is new to this project, but I had to also maintain the same style of error without using the same form logic, hence the copied and modified error ordered list below.

2021-04-16 05:03 UTC, dorianjp commented on outbreaks/views.py
> +            show_errors = True
this is used to hide errors on the form when not really submitting it by user intent

2021-04-16 05:06 UTC, dorianjp commented on outbreaks/views.py
> -    @transaction.atomic
this is not necessary with the atomic block already in place below

2021-04-16 05:19 UTC, dorianjp commented
![](https://github.trello.services/images/mini-trello-icon.png) [Improve interaction design of Date and time selection](https://trello.com/c/bNfAPtLt/704-improve-interaction-design-of-date-and-time-selection)

2021-04-19 17:49 UTC, dsamojlenko requested changes

2021-04-19 17:49 UTC, dsamojlenko commented on outbreaks/templates/datetime.html
> +                 href="{% url "outbreaks:datetime_delete" forloop.counter0 %}">{% trans "Delete" %}</a>
probably could use some visually-hidden text here to give context to screen readers

2021-04-19 17:49 UTC, dsamojlenko commented on outbreaks/templates/datetime.html
> +        </tr>
Should be in a `<thead>` element above `<tbody>`. Could also add a visually-hidden heading to the second column.

2021-04-19 21:07 UTC, dorianjp commented on outbreaks/templates/datetime.html
> +                 href="{% url "outbreaks:datetime_delete" forloop.counter0 %}">{% trans "Delete" %}</a>
updated, thanks!

2021-04-19 21:07 UTC, dorianjp commented on outbreaks/templates/datetime.html
> +        </tr>
done, thx

2021-04-20 14:29 UTC, dsamojlenko approved these changes
Looks good!

2021-04-20 15:25 UTC, EliseKa commented
Finished reviewing the translations!

2021-04-20 16:05 UTC, merged